### PR TITLE
Go rewrite

### PR DESCRIPTION
**Pull request by kiliankoe**
Why?

> Hubot is pretty awesome, no doubt, but running a node application eating loads of RAM (and crashing fairly often) is not so easy on our own hardware.
> A rewrite in go (a compiled and typed language), has the nice effect of producing a single statically-linked binary that can also be cross-compiled easily and run from any system, even the Raspberry Pi in our office.
### Still to migrate
- [x] random
- [x] ping
- [x] google images
- [x] simpleresponses (waiting for https://github.com/abourget/slick/issues/7)
- [x] fsr
- [x] firat
- [x] porn
- [x] version
- [x] mensa
- [x] dvb
- [x] urban dictionary
- [x] apbdoor
- [x] drsommer (wanted by anonymous other person^^)
- [x] stoll
- [x] basic bday stuff
- [x] btc
### Broken
- [x] elbe (API seems to be broken)
- [ ] geruecht (website is down)
### Probably unecessary

**ours:** dudle, qr, sudo_ger, video
**built-in:** dealwithit, weather, stallman, base64, catfacts, chm, coin, cowsay, flip, steveholt, wikipedia
**external:** diagnostics, help, google-translate, maps, redis-brain, rules, shipit, qr, calculator, xkcd, clarifai2
### Open/known issues
- [x] randomly occurring outgoing errors (write tcp my_ip:54821->54.165.249.88:443: i/o timeout)
- [x] current help plugin depends on slick fork
- [x] missing mensa emojis, depends on updated feed - @dirkonet?
- [x] vendor dependencies
- [x] do something about local paths not going to work after deploy (doesn't apply if it's only the conf file)
- [x] don't store porn names and other large amounts of content in code (actually, why not?)

### CODE REVIEW

**Comment by kiliankoe** [comment]
This is now more or less done. Three things are currently missing: elbe plugin (API is broken), geruecht plugin (website is broken) and mensa emojis (not supported by the new stuwe feed (yet)). As long as no new issues show up, I'd like to merge this soon :)

**Comment by kiliankoe** [comment]
elbe ✔️

**Comment by Feliix42** [comment]
He doesn't react to the keyword `matthias` anymore, if I see this right. Can you add this again? I prefer writing `matthias image me [...]` over `!image me [...]` because it feels more like talking to a participant of the conversation (but maybe that's just me...) :D

**Comment by kiliankoe** [comment]
Sorry, hubot had support for bot names and aliases. The current framework doesn't. It might be something to add on in the future, but currently all matchers are in the form of `!command`.

**Comment by kiliankoe** [comment]
I'll see if that's somehow feasible.

**Comment by kiliankoe** [comment]
matthias will now answer `!command` and `matthias command` for each normal command.

**Comment by kiliankoe** [comment]
If no new issues come up, I'm going to merge this and replace old matthias on the weekend.

**Review by mstuhlbein — APPROVED** [review]
LGTM 👍

**Comment by kiliankoe** [comment]
Everything is still looking good 👍 Looks like it's time for a merge 🎉

**Pull request merged**
