### PR TITLE
added image-support for food

### PR DESCRIPTION
**Pull request by heisig**

### CODE REVIEW

**Comment by kiliankoe** [comment]
```
matthias> matthias mensa alte
matthias> Heute @ *alte*:
0: Vier Quarkkäulchen mit Zucker und Apfelmus - 2€
1: Sauerbraten mit Apfelrotkohl und Kartoffelklößen - 2.5€
2: Gebackener Camembert mit  karamellisierten Birnen, Fladenbrot und Salat - 2.4€
3: Seelachswürfel und Kirschtomaten in Weißwein-Limonensoße auf Pasta - 2.8€
4: Pasta mit Tomatensoße mit Hirtenkäse
5: Pasta mit Champignons in Rahmsoße
6: Lasagne vom Pfannengemüse mit Gouda und Cheddar überbacken - 1.94€
7: Nudelgratin mit Tomate und Hirtenkäse - 1.94€
8: Nudelauflauf mit Pusztasoße und Käse - 1.94€

matthias> matthias mensa bild 0
matthias> No food with this number..

matthias> matthias mensa bild 1
matthias> http://bilderspeiseplan.studentenwerk-dresden.de/m18/201507/152394.jpg?date=201507311424
```

**Comment by kiliankoe** [comment]
```
matthias> matthias mensa bild 0
matthias> http:
```

**Comment by kiliankoe** [comment]
Whee \o/

**Comment by JustusAdam** [comment]
Wouldn't it be better if it were to fetch the image for the last mensa queried instead of only alte mensa?

**Comment by kiliankoe** [comment]
A specific keyword for that would be better I think. Otherwise matthias would have to save what the last query for every channel was.
But yeah, that's definitely an option for improving on this.

**Pull request merged**
