### PR TITLE
Added question response.

### PR DESCRIPTION
**Pull request by pibebtol**
¯\_(-.-)_/¯

### CODE REVIEW

**Comment by mstuhlbein** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by kiliankoe** [comment]
This was opened by accident, please ignore^^

**Comment by Feliix42** [comment]
And I got 4 mails for this! :old_man_yells_at_cloud:

**Comment by kiliankoe** [comment]
Which is *your fault* for watching the repo 😘

**Pull request closed without merging**
